all_countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Anguilla", "Antarctica",
                 "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan",
                 "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan",
                 "Bolivia", "Bonaire", "Bosnia and Herzegovina", "Botswana", "Brazil", "British Overseas Territories",
                 "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
                 "Chad", "Chile", "Colombia", "Costa Rica", "Croatia", "Cuba", "Curaçao", "Cyprus", "Denmark",
                 "Djibouti", "Dominica", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
                 "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "French Guiana",
                 "French Polynesia", "French Saint Martin", "Gabon", "Georgia (country)", "Germany", "Ghana",
                 "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
                 "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
                 "Indonesia", "Iran", "Iraq", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jersey", "Jordan",
                 "Kazakhstan", "Kenya", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Liberia", "Libya",
                 "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Madagascar", "mainland China", "Malawi",
                 "Malaysia", "Mali", "Malta", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Moldova",
                 "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia",
                 "Nepal", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea",
                 "North Macedonia", "Norway", "Oman", "Pakistan", "Panama", "Papua New Guinea", "Paraguay",
                 "Peru", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania", "Russia", "Rwanda", "Réunion",
                 "Saint Barthélemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia",
                 "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "San Marino", "Saudi Arabia",
                 "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia",
                 "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname",
                 "Sweden", "Switzerland", "Syria", "São Tomé and Príncipe", "Taiwan", "Tajikistan", "Tanzania",
                 "Thailand", "the Bahamas", "the British Virgin Islands", "the Cayman Islands",
                 "the Central African Republic", "the Czech Republic", "the Democratic Republic of the Congo",
                 "the Dominican Republic", "the Falkland Islands", "the Faroe Islands", "the Gambia", "the Isle of Man",
                 "the Maldives", "the Netherlands", "the Northern Mariana Islands", "the Philippines",
                 "the Republic of Ireland", "the Republic of the Congo", "the State of Palestine",
                 "the Turks and Caicos Islands", "the United Arab Emirates", "the United Kingdom", "the United States",
                 "the United States Virgin Islands", "the Åland Islands", "Togo", "Trinidad and Tobago", "Tunisia",
                 "Turkey", "Turkmenistan", "Uganda", "Ukraine", "Uruguay", "Uzbekistan", "Vatican City", "Venezuela",
                 "Vietnam", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]
